apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-backend-deployment
  labels:
    app: reviews-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews-backend
  template:
    metadata:
      labels:
        app: reviews-backend
    spec:
      containers:
      - name: reviews-backend
        image: 662585344222.dkr.ecr.us-east-1.amazonaws.com/reviews-backend:0.2
        ports:
        - containerPort: 80
