apiVersion: v1
kind: Secret
metadata:
  name: reviews-db-secret
  namespace: reviews-app
type: Opaque
data: 
  db_user: YWRtaW4=
  db_password: RGI+Yy1NLkM2VCRCd3U/Z1lBKjVVN1Q+IUc8Tg==
  db_host: cmV2aWV3cy1hcHAtZGItZGV2LmNsdXN0ZXItY3M1c2trNnFjY2d0LnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbQ==
  db_name: cmV2aWV3cy1hcHAtZGItZGV2