app_name: reviews-frontend 
image: 
  repo: 662585344222.dkr.ecr.us-east-1.amazonaws.com/reviews-frontend
  tag: "0.1"
replica_count: 1
port: 80
serviceType: LoadBalancer
resources:
  requests:
    cpu: 50m
    memory: 32Mi
  limits:
    cpu: 200m
    memory: 64Mi
ingress:
  enabled: true
  endpoint: reviews-dev.exchangeweb.net