{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.app_name }}-ingress"
spec:
  rules:
  - host: {{ .Values.ingress.endpoint }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "{{ .Values.app_name }}-service"
            port:
              number: {{ .Values.port }}
  ingressClassName: nginx
{{- end }}
