apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend-deployment
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: frontend-deployment
    spec:
      containers:
      - image: 401413892014.dkr.ecr.us-east-1.amazonaws.com/frontend:1.0
        name: frontend
        resources: {}
status: {}
