apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend-deployment
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: frontend-deployment
    spec:
      containers:
      - image: 662585344222.dkr.ecr.us-east-1.amazonaws.com/reviews-frontend:0.1
        name: frontend
        ports:
        - containerPort: 80