app_name: reviews-backend 
image: 
  repo: 662585344222.dkr.ecr.us-east-1.amazonaws.com/reviews-backend
  tag: "0.1"
replica_count: 1
port: 80
serviceType: LoadBalancer
resources: {}
ingress:
  enabled: true
  endpoint: reviews-api-dev.exchangeweb.net
env:
  - name: DB_USERNAME
    value: "admin"
  - name: DB_PASSWORD
    value: "password123"
  - name: DB_ENDPOINT
    valueFrom:
      secretKeyRef:
        name: reviews-backend-secret
        key: db_host