name: CI/CD for Reviews Application
on:
  push: 
    branches:
      - main 
      - 'feature/**'  

# permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read   # This is required for checking out the repository

jobs:
    deploy-app:
        environment: ${{ github.ref == 'refs/heads/main' && 'prod' || startsWith(github.ref, 'refs/heads/feature/') && 'dev' }}

        runs-on: ubuntu-22.04

        steps:
           - name: Checkout repository
             uses: actions/checkout@v3  

           - name: Login to AWS Role
             uses: aws-actions/configure-aws-credentials@v5.1.1
             with:
               aws-region: us-east-1
               role-to-assume: ${{ vars.IAM_ROLE }}
               role-session-name: gha-login-session

           - name: Login to Amazon ECR
             id: login-ecr
             uses: aws-actions/amazon-ecr-login@v2


           - name: Backend - Build, tag, and push docker image to Amazon ECR
             working-directory: ./api-backend/
             env:
                REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                REPOSITORY: reviews-backend
                IMAGE_TAG: 0.1
             run: |
                docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
                docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
            
           - name: Frontend - Build, tag, and push docker image to Amazon ECR
             working-directory: ./frontend/
             env:
                REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                REPOSITORY: reviews-frontend
                IMAGE_TAG: 0.1
             run: |
                docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
                docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          
           - name: Login to Kubernetes cluster
             run: |
                aws eks update-kubeconfig --name project-x-${{ vars.STAGE }}-tf-cluster
           
           - name: Deploy Backend to EKS
             run: |
                helm upgrade --install reviews-backend-app ./k8s-app/ --values ./k8s-app/backend/${{ vars.STAGE }}-values.yaml

           - name: Deploy Frontend to EKS 
             run: | 
                helm upgrade --install reviews-frontend-app ./k8s-app/ --values ./k8s-app/frontend/${{ vars.STAGE }}-values.yaml
                

          