name: CI/CD for Reviews Application
on:
  push: 
    branches:
      - main 
      - 'feature/**'  

# permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read   # This is required for checking out the repository

jobs:
    deploy-app:
        environment: ${{ github.ref == 'refs/heads/main' && 'prod' || startsWith(github.ref, 'refs/heads/feature/') && 'dev' }}

        runs-on: ubuntu-22.04

        steps:
           - name: Checkout repository
             uses: actions/checkout@v3  

           - name: Login to AWS Role
             uses: aws-actions/configure-aws-credentials@v5.1.1
             with:
               aws-region: us-east-1
               role-to-assume: ${{ vars.IAM_ROLE }}
               role-session-name: gha-login-session

           - name: Build backend image
             working-directory: ./api-backend/
             run:
                docker build -t reviews-backend:0.1 .

           - name: Login to AWS ECR
             run: | 
               aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 662585344222.dkr.ecr.us-east-1.amazonaws.com
              
           - name: Push imach to AWS ECR 
             run: |
                docker tag reviews-backend:0.1 662585344222.dkr.ecr.us-east-1.amazonaws.com/reviews-backend:0.1 
                docker push 662585344222.dkr.ec r.us-east-1.amazonaws.com/reviews-backend:0.1 
